// <auto-generated />
using AirlineService.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirlineService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220525154816_AirlineMigration")]
    partial class AirlineMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirlineService.Models.Airline", b =>
                {
                    b.Property<string>("AirlineNo");

                    b.Property<string>("ContactAddress");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("UploadLogo");

                    b.HasKey("AirlineNo");

                    b.ToTable("Airlines");
                });
#pragma warning restore 612, 618
        }
    }
}
